### ISSUE TITLE
Question: (not a bug)... Did you find gRPC limitations with GraalVM target?

### ISSUE THREAD

**Issue by ludoch** [hpehl/quarkus-grpc-extension#1]
Question: Did you find gRPC limitations with GraalVM target? Ii.e would you need changes in the gRPC libraries to make it better with a native target?
Thanks for doing this BTW!

**Comment by hpehl** [comment]
I've tested with the [route guide](
https://github.com/grpc/grpc-java/tree/v1.18.0/examples#grpc-examples) example (see [quarkus-grpc-quickstart](https://github.com/hpehl/quarkus-grpc-quickstart)) and didn't come across any issues so far. I did not change anything in the gRPC libs. 

However there were two issues during the implementation of this extension:

1. gRPC services cannot be proxied due to final methods in the generated gRPC service code. This makes it hard to integrate with CDI.
2. The generated code for messages depends on reflection. This is an issue in native mode. I've tried to use option `optimize_for = CODE_SIZE` (see https://developers.google.com/protocol-buffers/docs/reference/java-generated#message), but had issue to get it working.

**Comment by ludoch** [comment]
Related question: where the the graal vm settings should be located ?
In quarkus or on the core grpc lib? (via issue above?)

**Comment by hpehl** [comment]
Any improvements which make grpc-java more GraalVM friendly are of course welcome. For now in  Quarkus one can use the `@TargetClass` / `@Substitute` annotations to workaround certain limitations. This approach works quite well for the given limitations.

**Comment by hpehl** [comment]
Closing, since this extension is no longer supported. See README.md
